services:
  laravel-docker:
    container_name: laravel-demo-app
    build: .
    volumes: 
      - ./laravel-demo-app:/var/www/html
    ports:
      - 9007:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
    - 3309:3306


  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9008:80
    environment:
      - PMA_ARBITRARY=1